/// Flutter icons Navigation
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Navigation
///      fonts:
///       - asset: fonts/Navigation.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Navigation {
  Navigation._();

  static const _kFontFam = 'Navigation';
  static const _kFontPkg = null;

  static const IconData up_open = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
